# Generated by Django 5.0.3 on 2024-03-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.TextField(default='India'),
        ),
        migrations.AddField(
            model_name='location',
            name='humidity',
            field=models.TextField(default='50'),
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherApp.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherApp.owner')),
            ],
            options={
                'unique_together': {('user', 'location', 'condition')},
            },
        ),
    ]
